### ISSUE TITLE
UWP demo

### ISSUE THREAD

**Issue by hupo376787** [bitmovin/bitmovin-api-sdk-dotnet#1]
Hi, I'm using uwp. Is there any demo which I can use to play a video, I already have a key.

**Comment by seburgi** [comment]
I think you are looking for our Player demo project here: https://github.com/bitmovin/bitmovin-player-windows-app-demo Hope this helps :-) 

Will close this issue as it seems unrelated to our API SDK for .NET (this repo).

**Comment by hupo376787** [comment]
Hi, @seburgi , thank you for your response. We are using native API, not js. The repo you provided is based on js, this does not meet our requirements.
Can you provide a sample targeting to native controls, thanks.
